[tool.poetry]
name = "sample-project"
version = "0.0.1"
description = "sample description"
authors = ["Max Lee <pj4316@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
dependency-injector = "^4.41.0"
fastapi = ">=0.111.0,<0.112.0"
pydantic = "^2.5.3"
uvicorn = "~0.30.1"

# internal dependencies
libary1 = { path = "library/libary1", develop = true }
libary2 = { path = "library/libary2", develop = true }

[tool.poetry.group.dev.dependencies]
black = "^23.12.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pypi"
url = "https://pypi.org/simple"
priority = "primary"
